name: 'action-test action1'
description: 'action-test action1 description'
inputs:
  input1:
    description: 'input1 description'
    required: false
    default: 'INPUT1'
outputs:
  output1:
    description: 'output1 description'
    value: 'action1: ${{ inputs.input1 }}; ${{ steps.random-number-generator.outputs.random-id }}'
runs:
  using: 'composite'
  steps:
    - name: 'action-test action1 step1'
      run: |
        echo "step1/comm1"
        echo "step1/comm2"
      shell: bash
    - name: 'action-test action1 step2'
      id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
    - name: 'action-test action1 step3'
      run: |
        echo "step3/comm1"
        ${{ github.action_path }}/script1.sh
        echo 'github.action: ${{ github.action }}'
        echo 'github.action_path: ${{ github.action_path }}'
        echo 'github.event_name: ${{ github.event_name }}'
        echo 'github.job: ${{ github.job }}'
        echo 'github.repository: ${{ github.repository }}'
        echo 'github.workflow: ${{ github.workflow }}'
        echo 'github.workspace: ${{ github.workspace }}'
        echo 'github.event_path cat:'
        cat '${{ github.event_path }}'
        echo 'github.action_path ls:'
        ls -l '${{ github.action_path }}'
        echo 'step3 done.'
      shell: bash
