name: 'action-test action1'
description: 'action-test action1 description'
inputs:
  input1:
    description: 'input1 description'
    required: false
    default: 'INPUT1'
outputs:
  output1:
    description: 'output1 description'
    value: 'action1: ${{ inputs.input1 }}; ${{ steps.step2.outputs.out1 }}'
runs:
  using: 'composite'
  steps:
    - name: 'action-test action1 step1'
      run: |
        echo "step1 $(date '+%y%m%d-%H%M%S')"
        echo "step1/comm1"
        echo "step1/comm2"
      shell: bash
    - name: 'action-test action1 step2'
      id: step2
      run: |
        echo "out1=$(date '+%y%m%d-%H%M%S')" >> $GITHUB_ENV
      shell: bash
    - name: 'action-test action1 step3'
      run: |
        echo "step3/comm1"
        ${{ github.action_path }}/script1.sh '${{ github.workspace }}'
        echo 'github.action: ${{ github.action }}'
        echo 'github.action_path: ${{ github.action_path }}'
        echo 'github.event_name: ${{ github.event_name }}'
        echo 'github.job: ${{ github.job }}'
        echo 'github.repository: ${{ github.repository }}'
        echo 'github.workflow: ${{ github.workflow }}'
        echo 'github.workspace: ${{ github.workspace }}'
        #echo 'github.event_path cat:'
        #cat '${{ github.event_path }}'
        echo 'github.action_path ls:'
        ls -la '${{ github.action_path }}'
        echo 'step3 done.'
      shell: bash
